FROM public.ecr.aws/lambda/python@sha256:10dbb67ede15b5fd516be87dd71c3f7968904b0b840235720486476b34ef9b67 as build
RUN yum install -y unzip && \
    curl -Lo "/tmp/chromedriver.zip" "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip" && \
    curl -Lo "/tmp/chrome-linux.zip" "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1135561%2Fchrome-linux.zip?alt=media" && \
    unzip /tmp/chromedriver.zip -d /opt/ && \
    unzip /tmp/chrome-linux.zip -d /opt/

FROM public.ecr.aws/lambda/python@sha256:10dbb67ede15b5fd516be87dd71c3f7968904b0b840235720486476b34ef9b67
RUN yum install atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel -y
COPY --from=build /opt/chrome-linux /opt/chrome
COPY --from=build /opt/chromedriver /opt/

# Set environment variables
# Set the timezone
ENV TZ=Asia/Taipei
RUN ln -sf /opt/chromedriver /usr/local/bin/chromedriver
RUN ln -sf /opt/chrome/chrome /usr/local/bin/chrome


COPY requirements.txt ${LAMBDA_TASK_ROOT}
# Install requirements
RUN pip install -r requirements.txt


# Copy the contents of the current directory to the working directory in the container
COPY momocrawler ${LAMBDA_TASK_ROOT}/momocrawler
COPY lambda_function.py ${LAMBDA_TASK_ROOT}
COPY scrapy.cfg ${LAMBDA_TASK_ROOT}
CMD [ "lambda_function.handler" ]
